name: Update Concierge

on:
  schedule:
    - cron: '0/30 * * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
      
      - name: Install Chrome
        run: npx puppeteer browsers install chrome
      
      - name: Generate image
        run: node generate.js
        env:
          AIRBNB_ICAL_URL: ${{ secrets.AIRBNB_ICAL_URL }}
          WHATSAPP_PHONE: ${{ secrets.WHATSAPP_PHONE }}
          WIFI_SSID: ${{ secrets.WIFI_SSID }}
          WIFI_PASSWORD: ${{ secrets.WIFI_PASSWORD }}

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .

          git commit -m "Update concierge" || exit 0

          git push
