name: Update Concierge

on:
  schedule:
    - cron: '0/30 * * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Generate page
        run: node generate.js

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add .

          git commit -m "Update concierge" || exit 0

          git push
